Python program to create a 2d array with 1 on the border and 0 inside.

In [12]:
'''
@Author: Pavan Nakate
@Date: 2021-11-17 11:17
@Last Modified by: Pavan Nakate
@Last Modified time: None
@Title : Border of 1's  
'''
import numpy as np

try:
    arr = np.ones((5,5))
    print("Original Array:\n", arr)
    print("After Border: ")
    arr[1:-1, 1:-1] = 0
    print(arr)
    
except Exception as e:
    print(e)

Original Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside the array: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
