Python program to add a border filled with 0's around an existing array.

In [2]:
'''
@Author: Pavan Nakate
@Date: 2021-11-17 11:57
@Last Modified by: Pavan Nakate
@Last Modified time: None
@Title : Border of 0's  
'''
import numpy as np

try:
    arr = np.ones((3,3))
    print("Original array:\n",arr)
    print("After Border : ")
    arr2 = np.pad(arr, (1,), 'constant', constant_values = 0)
    print(arr2)
    
except Exception as e:
    print(e)

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
After Border : 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
