Python program to create a contiguous flattened array.

In [8]:
'''
@Author: Pavan Nakate
@Date: 2021-11-17 07:09
@Last Modified by: Pavan Nakate
@Last Modified time: None
@Title : ContigousArray  
'''
import numpy as np

try:
    arr1 = np.array([[10,20,30],[50,40,45]])
    print(arr1)
    arr2 = np.array([[60,70,80],[90,100,95]])
    print(arr2)
    print("With axis 0 : ",np.concatenate((arr1, arr2), axis=0))
    print("With axis 1 : ",np.concatenate((arr1, arr2), axis=1))
    print("Contiguous Array : ",np.concatenate((arr1,arr2), axis=None))

except Exception as e:
    print(e)

[[10 20 30]
 [50 40 45]]
[[ 60  70  80]
 [ 90 100  95]]
With axis 0 :  [[ 10  20  30]
 [ 50  40  45]
 [ 60  70  80]
 [ 90 100  95]]
With axis 1 :  [[ 10  20  30  60  70  80]
 [ 50  40  45  90 100  95]]
Contiguous Array :  [ 10  20  30  50  40  45  60  70  80  90 100  95]
