Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [3]:
'''
@Author: Pavan Nakate
@Date: 2021-11-17 07:20
@Last Modified by: Pavan Nakate
@Last Modified time: None
@Title : Create3DArray  
'''
import numpy as np

try:
    arr1 = np.eye(3)
    print("Array with ones on diagonal and zeros elsewhere:\n",arr1)
except Exception as e:
    print(e)

Array with ones on diagonal and zeros elsewhere:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
