Python program to how to add an extra column to an numpy array.

In [4]:
'''
@Author: Pavan Nakate
@Date: 2021-11-17 09:55
@Last Modified by: Pavan Nakate
@Last Modified time: None
@Title : ExtraColumn  
'''
import numpy as np

try:
    arr1 = np.array([[10,20,30], [50,60,70]])
    print("Before Adding : \n",arr1)
    arr2 = np.array([[40], [80]])
    arr3 = np.concatenate((arr1, arr2), axis=1)
    print("After Adding: ")
    print(arr3)
except Exception as e:
    print(e)

Before Adding : 
 [[10 20 30]
 [50 60 70]]
After Adding: 
[[10 20 30 40]
 [50 60 70 80]]
