Python program to convert a list and tuple into arrays.

In [2]:
'''
@Author: Pavan Nakate
@Date: 2021-11-17 06:05
@Last Modified by: Pavan Nakate
@Last Modified time: None
@Title : ListTupleConversion  
'''
import numpy as np

try:
    arr = np.array([1,2,3,4,5,6,7,8])
    print("List to array:\n", arr )

    arr1 = np.array([[1,2,3],[4,5,6]])
    print("Tuple to array:\n",arr1)
except Exception as e:
    print(e)

List to array:
 [1 2 3 4 5 6 7 8]
Tuple to array:
 [[1 2 3]
 [4 5 6]]
